apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: mq-hello-world
  namespace: henda
spec:
  params:
  - name: git-url
    value: 'https://github.com/hindos/mq-custom-cp4i.git'
  - name: app-namespace
    value: henda
  - name: app-name
    value: mq-custom-cp4i
  - name: private-lan-id
    value: ""
  - name: private-ip
    value: ""
  - name: deployment-type
    value: siqm
  - name: siqm-primary
    value: "1"
  - name: siqm-secondary
    value: "2"
  - name: storage-class
    value: ibmc-block-gold
  - name: storage-size
    value: 20Gi
  - name: config-map
    value: ""
  - name: qmgr-name
    value: QM1
  - name: master-image
    value: "false"    
  - name: environment
    value: "dev"    
  pipelineRef:
    name: mq-pipeline-sample
  serviceAccountName: pipeline
  timeout: 1h30m
